### ISSUE TITLE
Cannot sync repo init -u https://github.com/BlissRoms-x86/manifest.git -b n7.1.1-x86

### ISSUE THREAD

**Issue by getfeus** [BlissRoms-x86/manifest#22]
I am trying to build n7.1.1-x86. But sync process(with repo sync --no-tags --no-clone-bundle command) is failed with next output.

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * [new tag]           android-7.1.1_r28 -> android-7.1.1_r28
Fetching project platform/prebuilts/gradle-plugin
remote: Sending approximately 2.36 GiB ...
remote: Counting objects: 1, done
remote: Finding sources: 100% (37865/37865)
remote: Total 37865 (delta 8190), reused 36119 (delta 8190)
Receiving objects: 100% (37865/37865), 754.49 MiB | 11.11 MiB/s, done.
Resolving deltas: 100% (8190/8190), done.
From https://android.googlesource.com/platform/prebuilts/gradle-plugin
 * [new tag]           android-7.1.1_r28 -> android-7.1.1_r28
Fetching project aosp_build
Username for 'https://github.com': ~~~
Password for '~~~@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/BlissRoms-x86/aosp_build/' not found
Username for 'https://github.com': ~~~
Password for '~~~@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/BlissRoms-x86/aosp_build/' not found
error: Cannot fetch aosp_build

error: Exited sync due to fetch errors
```

Thank you for reading.

**Comment by getfeus** [comment]
Line 138~141's branch name looks like incorrect.
Need to chagne
`<project path="vendor/google/build" name="aosp_build" revision="master" remote="BR-x86" />`
to
`<project path="vendor/google/build" name="aosp_build" revision="master" remote="opengapps" />`

Please check this solution is correct or not.

PS. I found that cannot sync to n7.1.1-x86-dev also.
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * [new tag]         android-7.1.1_r12 -> android-7.1.1_r12
Fetching project platform/external/google-benchmark
remote: Counting objects: 1, done
remote: Finding sources: 100% (1831/1831)
remote: Total 1831 (delta 1212), reused 1759 (delta 1212)
Receiving objects: 100% (1831/1831), 324.85 KiB | 1.80 MiB/s, done.
Resolving deltas: 100% (1212/1212), done.
From https://android.googlesource.com/platform/external/google-benchmark
 * [new tag]         android-7.1.1_r12 -> android-7.1.1_r12
Fetching project kernel_common
fatal: Couldn't find remote ref refs/heads/kernel-4.10rc3
fatal: Couldn't find remote ref refs/heads/kernel-4.10rc3
error: Cannot fetch kernel_common

error: Exited sync due to fetch errors

```

**Comment by electrikjesus** [comment]
That solution is correct. We haven't revisited nougat since moving
development to Oreo, so if you'd like to make a pull request, please feel
free and we will merge accordingly

**Comment by getfeus** [comment]
to @electrikjesus 
Thank you very much for your review. I will make pull request to fix the problem.

It looks like oreo repository is disappeared. Is it changed to hidden repository? 

Best regards.

**Comment by getfeus** [comment]
I can sync with my modification to manifest.xml. 

But, I cannot build source. (I will attach error)

```
linux-server BlissRoms-n7.1.1-x86 # lunch bliss_android_x86_64-userdebug
ls: cannot access 'device/*/android_x86_64/bliss.mk': No such file or directory
build/core/product_config.mk:244: *** Can not locate config makefile for product "bliss_android_x86_64".  Stop.
ls: cannot access 'device/*/android_x86_64/bliss.mk': No such file or directory
build/core/product_config.mk:244: *** Can not locate config makefile for product "bliss_android_x86_64".  Stop.
your device can't be found in device sources..
found the android_x86_64 device repo
your device can't be found in device sources..
Traceback (most recent call last):
  File "build/tools/roomservice.py", line 317, in <module>
    fetch_dependencies(device)
  File "build/tools/roomservice.py", line 270, in fetch_dependencies
    raise Exception("ERROR: could not find your device "
Exception: ERROR: could not find your device folder location, bailing out
ls: cannot access 'device/*/android_x86_64/bliss.mk': No such file or directory
build/core/product_config.mk:244: *** Can not locate config makefile for product "bliss_android_x86_64".  Stop.

** Don't have a product spec for: 'bliss_android_x86_64'
** Do you have the right repo manifest?

linux-server BlissRoms-n7.1.1-x86 # lunch android_x86_64-userdebug
build/core/product_config.mk:263: *** No matches for product "android_x86_64".  Stop.
build/core/product_config.mk:263: *** No matches for product "android_x86_64".  Stop.
WARNING: Trying to fetch a device that's already there
WARNING: device/generic/x86_64/bliss.dependencies file not found
build/core/product_config.mk:263: *** No matches for product "android_x86_64".  Stop.

** Don't have a product spec for: 'android_x86_64'
** Do you have the right repo manifest?

linux-server BlissRoms-n7.1.1-x86 # ls ./device/generic/x86_64/
AndroidProducts.mk  BoardConfig.mk  android_x86_64.mk  bliss.mk  vendorsetup.sh
```

Now, I am checking build repository's source and device_generic_* repository's source. Definition of androit_x86_64.mk is present on ./device/generic/x86_64/ dir. I think lunch android_x86_64-userdebug command must success but failed.
